MACRO(GENERATE_SUBDIRS result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(names "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
		IF (NOT ${child} MATCHES "\\..*")
			if(EXISTS ${curdir}/${child}/CMakeLists.txt)
				string(REPLACE " " "_" child ${child})
				SET(names ${names} ${child})
				message("BUILD FOR '${child}' GENERATED")
			endif()
		ENDIF()
    ENDIF()
  ENDFOREACH()
  SET(${result} ${${result}} ${names})
  	FOREACH(n ${names})
  		add_subdirectory(${curdir}/${n})
  	ENDFOREACH()
ENDMACRO()